import Sidebar from "@/components/Sidebar/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import Links from "@/components/Sidebar/Links";
import Image from "next/image";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-5 gap-8  ">
          <div className="col-span-1 bg-white font-bold shadow-lg p-10  h-screen ">
            <Links></Links>
          </div>
          <div className="col-span-4 mt-8">
            <div className="mr-8">
              <Header></Header>
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
